/*
	generated by GenerateAst.js

	interface Visitor<R> {
		 R visitFunctionStmt(Visitor<Function> visitor)
		 R visitWhileStmt(Visitor<While> visitor)
		 R visitIfStmt(Visitor<If> visitor)
		 R visitBlockStmt(Visitor<Block> visitor)
		 R visitExpressionStmt(Visitor<Expression> visitor)
		 R visitPrintStmt(Visitor<Print> visitor)
		 R visitVarStmt(Visitor<Var> visitor)
		 R visitReturnStmt(Visitor<Return> visitor)
	}
*/

/* abstract class */
class Stmt {
	accept (visitor) {}
}

class Function extends Stmt {
	constructor(name,params,body) {
		super()
		this.name = name
		this.params = params
		this.body = body
	}

	/* Function accept(Visitor<Function> visitor) */
	accept(visitor) {
		return visitor.visitFunctionStmt(this)
	}
}

class While extends Stmt {
	constructor(condition,body) {
		super()
		this.condition = condition
		this.body = body
	}

	/* While accept(Visitor<While> visitor) */
	accept(visitor) {
		return visitor.visitWhileStmt(this)
	}
}

class If extends Stmt {
	constructor(condition,thenBranch,elseBranch) {
		super()
		this.condition = condition
		this.thenBranch = thenBranch
		this.elseBranch = elseBranch
	}

	/* If accept(Visitor<If> visitor) */
	accept(visitor) {
		return visitor.visitIfStmt(this)
	}
}

class Block extends Stmt {
	constructor(statements) {
		super()
		this.statements = statements
	}

	/* Block accept(Visitor<Block> visitor) */
	accept(visitor) {
		return visitor.visitBlockStmt(this)
	}
}

class Expression extends Stmt {
	constructor(expression) {
		super()
		this.expression = expression
	}

	/* Expression accept(Visitor<Expression> visitor) */
	accept(visitor) {
		return visitor.visitExpressionStmt(this)
	}
}

class Print extends Stmt {
	constructor(expression) {
		super()
		this.expression = expression
	}

	/* Print accept(Visitor<Print> visitor) */
	accept(visitor) {
		return visitor.visitPrintStmt(this)
	}
}

class Var extends Stmt {
	constructor(name,initializer) {
		super()
		this.name = name
		this.initializer = initializer
	}

	/* Var accept(Visitor<Var> visitor) */
	accept(visitor) {
		return visitor.visitVarStmt(this)
	}
}

class Return extends Stmt {
	constructor(keyword,value) {
		super()
		this.keyword = keyword
		this.value = value
	}

	/* Return accept(Visitor<Return> visitor) */
	accept(visitor) {
		return visitor.visitReturnStmt(this)
	}
}

module.exports = {
	Function,
	While,
	If,
	Block,
	Expression,
	Print,
	Var,
	Return
}